package events;

public enum EventType
{
	NEXT_TURN, NEW_TURN, DEPLOYING_UNIT, MOVING_UNIT, PLACE_DEPLOY_POINT, COMBAT,
	UNITBASEATTACK, FINISH_ACTION, ARTILLERY_HIT, ARTILLERY_WITHOUT_HIT, ARTILLERY_BLOCKED, SKIP_TURN, CREDITS_CHANGE;
}
